AWSTemplateFormatVersion: 2010-09-09
Parameters:
  chaosWebsiteS3Bucket:
    Description: The name of the bucket to store the static website files
    Type: String
  chaosLambdaS3Bucket:
    Description: The name of the bucket to store the lambda function code during deployment
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName:
        # refer to chaos-website-deployer code to work out how this param is passed
        Ref: chaosWebsiteS3Bucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    Type: AWS::S3::Bucket
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: ChaosQoalaS3WebSitePolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
      Bucket: !Ref S3Bucket
  S3LambdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        # refer to chaos-website-deployer code to work out how this param is passed
        Ref: chaosLambdaS3Bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content